### ISSUE TITLE
Search does not work

### ISSUE THREAD

**Issue by tkestowicz** [jasonnutter/vscode-search-node-modules#2]
Hi,

I installed this extension in VS Code 1.9.1 and when I select "search node_modules" command nothing happens (see  #screen). It looks like it doesn't see node_modules folder or it is unable to list modules which sits there. Maybe there are too many packages (~750)?

![image](https://cloud.githubusercontent.com/assets/4162924/23222516/6b66d120-f928-11e6-9889-f865cba52295.png)

**Comment by jasonnutter** [comment]
@tkestowicz Sorry for the delay in responding. This is likely due to the extension unable to access the `node_modules` folder (e.g. it doesn't exist). The next update will include better error handling for this.

I don't think the problem is the number of packages. I wonder if it might be a permissions issue? If not, can you tell what OS you are on? That and your `package.json` would be helpful to try to reproduce.
